### ISSUE TITLE
Screenshot Screen and Camera

### ISSUE THREAD

**Issue by spectre12271024** [Sav1030/screen-and-photo-taking-demo#1]
Hello, I`d like to know about this project

**Comment by Sav1030** [comment]
U can use this to take camera capture and screenshot using a button

**Comment by spectre12271024** [comment]
Oh, Understand
I will check

**Comment by Sav1030** [comment]
but it is too simple 
need some update

**Comment by spectre12271024** [comment]
I will complete your project UI

**Comment by spectre12271024** [comment]
Ok!!!
Wonderful
Perfect!!!!!

**Comment by spectre12271024** [comment]
Thank you
